- name: Run Docker container
  hosts: containers
  become: true
  tasks:
    - name: Pull Docker image
      docker_image:
        name: yuvrajsharma2000/docker_image_calculator
        source: pull

    - name: Run Docker container
      docker_container:
        name: my-calculator
        image: yuvrajsharma2000/docker_image_calculator
        state: started  
