- name: Run Docker container
  hosts: containers
  become: true
  tasks:
    - name: Log in to Docker Hub
      docker_login:
        registry_url: https://index.docker.io/v1/
        username: "{{ jenkins_credentials_username }}"
        password: "{{ jenkins_credentials_password }}"

    - name: Pull Docker image
      docker_image:
        name: yuvrajsharma2000/docker_image_calculator
        source: pull

    - name: Run Docker container
      docker_container:
        name: my-calculator
        image: yuvrajsharma2000/docker_image_calculator
        state: started  
        command: docker run -it yuvrajsharma2000/docker_image_calculator /bin/bash
